language: node_js
node_js:
  - '0.10'
script:
  - 'npm test'
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || ./scripts/deploy_docs_from_travis.sh'
env:
  global:
    - GH_REF: 'github.com/killercup/grock.git'
    - secure: 'VpmToJzuKEC9CqkBxBd7ZoH2h56rlNo0TW4s9kdbc1MeHela0UhERFlDPGSVv+ByQ0ALeN7OeueSlrOOBymVXSI5Z4sQ0WwppDCXfYNPOO97kyFLrJ8NRM5vtPIcIDCR8LLpkAG+UKSXpDsBwASioxqXikouhA8XS0cCkz+sb2g='
